language: go

go:
  - 1.16.x

services:
  - docker

install:
  - ./lint.sh

script:
  - go get
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
  - export TAG="${TRAVIS_PULL_REQUEST_BRANCH:-latest}"
  - docker build -t ${DOCKER_REGISTRY}/eq-questionnaire-launcher:"$TAG" -t onsdigital/eq-questionnaire-launcher:"$TAG" .
  - echo "$DOCKER_GCR_PASSWORD" | base64 --decode | docker login -u "$DOCKER_GCR_USERNAME" --password-stdin https://eu.gcr.io
  - echo "Pushing to GCR with tag [$TAG]"
  - docker push ${DOCKER_REGISTRY}/eq-questionnaire-launcher:"$TAG"
  - echo "Pushing to Docker Hub with tag [$TAG]"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push onsdigital/eq-questionnaire-launcher:"$TAG"
branches:
  only:
    - master
