# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ""
  tag: ""
  pullPolicy: Always

surveyRunnerUrl: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

targetNodePool: "main-node-pool"